# Site settings
title: Aluya Resume
email: aghoghoaluya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: Shoutaluya
github_username: Shoutaluya

# Build settings
markdown: kramdown
